---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ieiy6387/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R robots.txt $DEPLOYPATH
    - /bin/cp -R sitemap.xml $DEPLOYPATH
